Helperland/Controllers/BookServiceController.cs
using Helperland.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using Helperland.Models;
using System.Net.Mail;
using System.Net;

namespace Helperland.Controllers
{
    public class BookServiceController : Controller
    {
        private readonly Data.ApplicationDbContext _db;
        private string zipcode;

        public BookServiceController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        
        [HttpGet]
        public string SerchZipcode(string ZipCode)
        {

            var userData = _db.Users.Where(x => x.UserId.Equals(HttpContext.Session.GetInt32("userid"))).FirstOrDefault();
            if (userData != null && userData.UserTypeId.Equals(1))
            {
                if (ZipCode != null)
                {
                    zipcode = ZipCode;
                    var data = _db.Zipcodes.Where(x => x.ZipcodeValue.Equals(ZipCode)).FirstOrDefault();
                    var data2 = _db.Users.Where(x => x.ZipCode.Equals(ZipCode) && x.UserTypeId.Equals(2)).FirstOrDefault();
                    if (data != null && data2 != null)
                    {
                        return "true";
                    }
                    else
                    {
                        return "false";
                    }
                }
                return "false";
            }
            return "login";
        }

        [HttpGet]
        public IActionResult GetAddress()
        {
            System.Threading.Thread.Sleep(2000);
            return View(_db.UserAddresses.Where(x => x.UserId.Equals(HttpContext.Session.GetInt32("userid"))).ToList());
            //Address address = new Address();
            //address.Address1 = "Hedge End";
            //return View(address);
        }

        [HttpPost]
        public IActionResult AddAddress(UserAddress objuser)
        {
            if (ModelState.IsValid)
            {
                _db.UserAddresses.Add(objuser);
                _db.SaveChanges();
                return Json(true);
            }
            return Json(false);
        }

        [HttpPost]
        public JsonResult AddRequest(ServiceRequestModel booking)
        {
            if(booking != null)
            {
                ServiceRequest request = new ServiceRequest
                {
                    UserId = booking.UserId,
                    ServiceStartDate = booking.ServiceStartDate,
                    ZipCode = booking.ZipCode,
                    ServiceHourlyRate = booking.ServiceHourlyRate,
                    ServiceHours = booking.Hours,
                    ExtraHours = booking.ExtraHours,
                    SubTotal = booking.SubTotal,
                    TotalCost = booking.TotalCost,
                    Comments = booking.Comments,
                    HasPets = booking.HasPets,
                    CreatedDate = DateTime.Now,
                    ModifiedDate = DateTime.Now,
                    Distance = 0
                };
                _db.ServiceRequests.Add(request);
                _db.SaveChanges();
                var requestId = request.ServiceRequestId;
                return Json(new { id = requestId.ToString() });
            }
            return Json(false);
        }

        public JsonResult AddExtra(int ServiceId, int ExtraId)
        {
            ServiceRequestExtra requestExtra = new ServiceRequestExtra
            {
                ServiceRequestId = ServiceId,
                ServiceExtraId = ExtraId
            };
            _db.ServiceRequestExtras.Add(requestExtra);
            _db.SaveChanges();
            return Json(true);
        }


        public JsonResult AddServiceAddress(int ServiceId, int AddressId)
        {
            var AddressData = _db.UserAddresses.Where(x => x.AddressId.Equals(AddressId)).FirstOrDefault();
            ServiceRequestAddress requestAddress = new ServiceRequestAddress
            {
                ServiceRequestId = ServiceId,
                AddressLine1 = AddressData.AddressLine1,
                AddressLine2 = AddressData.AddressLine2,
                City = AddressData.City,
                State = AddressData.State,
                PostalCode = AddressData.PostalCode,
                Mobile = AddressData.Mobile,
                Email = AddressData.Email
            };
            _db.ServiceRequestAddresses.Add(requestAddress);
            _db.SaveChanges();
            var Providers = _db.Users.Where(x => x.ZipCode.Equals(AddressData.PostalCode) && x.UserTypeId.Equals(2)).ToList();

            
            foreach(var provider in Providers)
            {
                var subject = "Service Request from Helperland";
                var body = "Hi " + provider.FirstName + "Customer has booked Service at your Area. <br> You can take that service " +
                    "by login in helperland account.<br>" +
                    "Thankyou";
                SendEmail(provider.Email, body, subject);
            }


            return Json(true);
        }

        private void SendEmail(string emailAddress, string body, string subject)
        {
            using (MailMessage mm = new MailMessage("mmthadiya@gmail.com", emailAddress))
            {
                mm.Subject = subject;
                mm.Body = body;

                mm.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.EnableSsl = true;
                NetworkCredential networkCred = new NetworkCredential("mmthadiya@gmail.com", "MMta00Hdya");
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = networkCred;
                smtp.Port = 587;
                smtp.Send(mm);
            }
        }

    } 
}

Helperland/Views/BookService/AddressForm.cshtml
@model Helperland.Models.UserAddress
@{
    Layout = null;
}
@using Microsoft.AspNetCore.Http;
<div>
    <form id="AddressForm" method="post" asp-action="AddAddress" asp-controller="BookService">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="UserId" class="form-control" id="UserId" value="@Context.Session.GetInt32("userid")" hidden />

        <div class="row">
            <div class="col-md-6 col-12">
                <label asp-for="AddressLine1">Street name*</label>
                <input asp-for="AddressLine1" class="form-control" id="AddressLine1" placeholder="Street name" />
                <span asp-validation-for="AddressLine1" class="text-danger"></span>

            </div>
            <div class="col-md-6 col-12">
                <label asp-for="AddressLine2">House number*</label>
                <input asp-for="AddressLine2" class="form-control" id="AddressLine2" placeholder="House number" />
                <span asp-validation-for="AddressLine2" class="text-danger"></span>
            </div>
        </div>
        <div class="row  mt-3">
            <div class="col-md-6 col-12">
                <label asp-for="PostalCode">Postal Code*</label>
                <input asp-for="PostalCode" name="PostalCode" class="form-control" id="Zip" readonly />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="col-md-6 col-12">
                <label asp-for="City">City*</label>
                <input asp-for="City" class="form-control" id="City" placeholder="Surat">
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-6 col-12">
                <label asp-for="Mobile">Phone number*</label>
                <div class="input-group">
                    <span class="input-group-text">+49</span>
                    <input asp-for="Mobile" class="form-control" id="Mobile" placeholder="Phone No">
                    <span asp-validation-for="Mobile" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="float-left mt-3 ml-1">
            <button class="btn btn-success rounded-pill px-4" onclick="ValidateForm();">Save</button>
        </div>
    </form>
    <div class="float-left mt-3">
        <button class="btn btn-outline-danger rounded-pill ml-2 px-4" onclick="RemoveForm();">Cancel</button>
    </div>
</div>

Helperland/Views/BookService/GetAddress.cshtml
@model IEnumerable<Helperland.Models.UserAddress>

@{
    Layout = null;
}
@*@model Helperland.Controllers.Address
    Street: @Html.TextBoxFor(m => m.Address1)
    <br />*@

<p><b>Enter your contact details, so we can serve you in better way!</b></p>
@foreach (var item in Model)
{
    <div class="AddressList mt-2">
        <div class="form-check">
            <input class="form-check-input mt-3" type="radio" name="Address" value="@Html.DisplayFor(modelItem => item.AddressId)" />
            <label class="form-check-label ml-2">
                <b>Address:</b>@Html.DisplayFor(modelItem => item.AddressLine1)
                @Html.DisplayFor(modelItem => item.AddressLine2),@Html.DisplayFor(modelItem => item.City) @Html.DisplayFor(modelItem => item.PostalCode)<br />
                <b>Phone number:</b>@Html.DisplayFor(modelItem => item.Mobile)
            </label>
        </div>
    </div>
}