Helperland/Controllers/ServiceProviderController.cs
using Helperland.Data;
using Helperland.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Web;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Drawing;


namespace Helperland.Controllers
{
    public class ServiceProviderController : Controller
    {
        private readonly Data.ApplicationDbContext _db;

        public ServiceProviderController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("userid") != null)
            {
                var user = _db.Users.Where(x => x.UserId.Equals(HttpContext.Session.GetInt32("userid"))).FirstOrDefault();
                ViewBag.Firstname = user.FirstName;
                return View();
            }
            return RedirectToAction("Login", "Account");
        }

        public IActionResult Tab2Content()
        {
            var provider = _db.Users.Where(x => x.UserId.Equals(HttpContext.Session.GetInt32("userid"))).FirstOrDefault();
            List<User> users = _db.Users.ToList();
            List<ServiceRequest> requests = _db.ServiceRequests.ToList();
            List<ServiceRequestAddress> addresses = _db.ServiceRequestAddresses.ToList();
            var record = from a in requests
                         join b in addresses on a.ServiceRequestId equals b.ServiceRequestId into table1
                         from b in table1.ToList()
                         join c in users on a.UserId equals c.UserId into table2
                         from c in table2.Where(x => a.ServiceStartDate > DateTime.Now && a.Status != 3 && a.Status != 2 && a.ZipCode.Equals(provider.ZipCode)).ToList()
                         select new ViewModel
                         { 
                             serviceRequest=a,
                             requestAddress=b,
                             user=c
                         };
            
            return View(record);
        }

        public IActionResult Tab3Content()
        {
            var provider = _db.Users.Where(x => x.UserId.Equals(HttpContext.Session.GetInt32("userid"))).FirstOrDefault();
            List<User> users = _db.Users.ToList();
            List<ServiceRequest> requests = _db.ServiceRequests.ToList();
            List<ServiceRequestAddress> addresses = _db.ServiceRequestAddresses.ToList();
            var record = from a in requests
                         join b in addresses on a.ServiceRequestId equals b.ServiceRequestId into table1
                         from b in table1.ToList()
                         join c in users on a.UserId equals c.UserId into table2
                         from c in table2.Where(x => a.ServiceProviderId.Equals(HttpContext.Session.GetInt32("userid")) && a.Status == 3).ToList()
                         select new ViewModel
                         {
                             serviceRequest = a,
                             requestAddress = b,
                             user = c
                         };
            return View(record);
        }

        public IActionResult Tab5Content()
        {
            List<User> users = _db.Users.ToList();
            List<ServiceRequest> requests = _db.ServiceRequests.ToList();
            List<ServiceRequestAddress> addresses = _db.ServiceRequestAddresses.ToList();
            var record = from a in requests
                         join b in addresses on a.ServiceRequestId equals b.ServiceRequestId into table1
                         from b in table1.ToList()
                         join c in users on a.UserId equals c.UserId into table2
                         from c in table2.Where(x => a.ServiceProviderId.Equals(HttpContext.Session.GetInt32("userid")) && a.ServiceStartDate < DateTime.Now.AddHours(Convert.ToDouble(a.SubTotal))).ToList()
                         select new ViewModel
                         {
                             serviceRequest = a,
                             requestAddress = b,
                             user = c
                         };
            return View(record);
        }

        public FileResult DownloadExcel()
        {
            List<User> users = _db.Users.ToList();
            List<ServiceRequest> requests = _db.ServiceRequests.ToList();
            List<ServiceRequestAddress> addresses = _db.ServiceRequestAddresses.ToList();
            var record = from a in requests
                         join b in addresses on a.ServiceRequestId equals b.ServiceRequestId into table1
                         from b in table1.ToList()
                         join c in users on a.UserId equals c.UserId into table2
                         from c in table2.Where(x => a.ServiceProviderId.Equals(HttpContext.Session.GetInt32("userid")) && a.ServiceStartDate < DateTime.Now.AddHours(Convert.ToDouble(a.SubTotal))).ToList()
                         select new ViewModel
                         {
                             serviceRequest = a,
                             requestAddress = b,
                             user = c
                         };

            ExcelPackage Ep = new ExcelPackage();
            ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
            Sheet.Cells["A1"].Value = "Service Id";
            Sheet.Cells["B1"].Value = "Service Date";
            Sheet.Cells["C1"].Value = "Customer Details";
            int row = 2;
            foreach(var item in record)
            {
                Sheet.Cells[String.Format("A{0}", row)].Value = item.serviceRequest.ServiceRequestId;
                Sheet.Cells[String.Format("B{0}", row)].Value = item.serviceRequest.ServiceStartDate.ToShortDateString() + "\n" + item.serviceRequest.ServiceStartDate.ToShortTimeString() +" - " + item.serviceRequest.ServiceStartDate.AddHours(Convert.ToDouble(item.serviceRequest.SubTotal)).ToShortTimeString();
                Sheet.Cells[String.Format("C{0}", row)].Value = item.user.FirstName + " " + item.user.LastName + "\n"
                    + item.requestAddress.AddressLine1 +" "+ item.requestAddress.AddressLine2 + "\n" + item.requestAddress.PostalCode +" "+ item.requestAddress.City;
                row++;
            }

            Sheet.Cells["A:AZ"].AutoFitColumns();
            using (MemoryStream stream = new MemoryStream())
            {
                Ep.SaveAs(stream);
                return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ServiceHistory.xlsx");
            }
            
            
        }

        public IActionResult Tab6Content()
        {

            List<User> users = _db.Users.ToList();
            List<ServiceRequest> requests = _db.ServiceRequests.ToList();
            List<Rating> ratings = _db.Ratings.ToList();
            var record = from a in requests
                         join b in ratings on a.ServiceRequestId equals b.ServiceRequestId into table1
                         from b in table1.ToList()
                         join c in users on a.UserId equals c.UserId into table2
                         from c in table2.Where(x => a.ServiceProviderId.Equals(HttpContext.Session.GetInt32("userid"))).ToList()
                         select new ViewModel
                         {
                             serviceRequest = a,
                             rating = b,
                             user = c
                         };
            return View(record);
        }

        public IActionResult Tab7Content()
        {
            List<User> users = _db.Users.ToList();
            List<ServiceRequest> requests = _db.ServiceRequests.ToList();
            var record = from a in requests
                         join b in users on a.UserId equals b.UserId into table2
                         from b in table2.Where(x => a.ServiceProviderId.Equals(HttpContext.Session.GetInt32("userid")) && a.Status.Equals(1)).ToList()
                         select new ViewModel
                         {
                             serviceRequest = a,
                             user = b
                         };
            return View(record); 
        }
        
        public IActionResult MySetting()
        {
            return View(_db.Users.Where(x => x.UserId.Equals(HttpContext.Session.GetInt32("userid"))).FirstOrDefault());
        }

        public JsonResult Service(int Id)
        {
            var datas = _db.ServiceRequests.Where(x => x.ServiceRequestId.Equals(Id)).FirstOrDefault();
            var user = _db.Users.Where(x => x.UserId.Equals(datas.UserId)).FirstOrDefault();
            var Name = user.FirstName + " " + user.LastName;
            var AddressData = _db.ServiceRequestAddresses.Where(x => x.ServiceRequestId.Equals(Id)).FirstOrDefault();
            var address = AddressData.AddressLine1 + " " + AddressData.AddressLine2 + ", " + AddressData.PostalCode + " " + AddressData.City;
            var Extra = _db.ServiceRequestExtras.Where(x => x.ServiceRequestId.Equals(Id)).ToList();
            var AllExtra = "";
            foreach (var item in Extra)
            {
                AllExtra = AllExtra + GetExtraName(item.ServiceExtraId);
            }
            return Json(new
            {
                serviceid = datas.ServiceRequestId,
                servicedate = datas.ServiceStartDate.ToString(),
                subtotal = datas.SubTotal,
                extra = AllExtra,
                addresses = address,
                duration = datas.ServiceHours,
                cname = Name,
                distance = datas.Distance,
                total = datas.TotalCost,
                cmnt = datas.Comments
            });
        }

        public JsonResult ServiceAccept(int Id)
        {

Helperland/Views/ServiceProvider/Index.cshtml
@{
    ViewData["Title"] = "Service Provider Page";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}
<link href="~/css/Service.css" rel="stylesheet" />

<div class="welcome_name">
    <center><h2>Welcome,<b> @ViewBag.Firstname </b></h2></center>
</div>
<section>
    <div class="menu_content" style="height:820px;">
        <div class="sidebar">
            <a id="tab1" class="link active-link" onclick="Tab1Click()"> Dashboard</a>
            <a id="tab2" class="link" onclick="Tab2Click()"> New Service Requests</a>
            <a id="tab3" class="link" onclick="Tab3Click()"> Upcoming Services</a>
            <a id="tab4" class="link" onclick="Tab4Click()"> Service Schedule</a>
            <a id="tab5" class="link" onclick="Tab5Click()"> Service History</a>
            <a id="tab6" class="link" onclick="Tab6Click()"> My Ratings</a>
            <a id="tab7" class="link" onclick="Tab7Click()"> Block Customer</a>
            <a> Invoices</a>
            <a> Notifications</a>
        </div>

        <!-- Page content -->
        <div class="content">
            <div id="tabContent1">
                <p>No data Avalable</p>
            </div>
            <div id="tabContent2" style="display:none">

            </div>
            <div id="tabContent3" style="display:none">

            </div>
            <div id="tabContent4" style="display:none">
                <p>No data Avalable</p>
            </div>
            <div id="tabContent5" style="display:none">

            </div>
            <div id="tabContent6" style="display:none">

            </div>
            <div id="tabContent7" style="display:none">

            </div>
            <div id="MySetting" style="display:none">

            </div>
        </div>

    </div>
</section>


<script>
    function Tab1Click() {
        var x = "#" + "tabContent1";
        $("#tab1").addClass("active-link");
        $("#tab2").removeClass("active-link").addClass("link");
        $("#tab3").removeClass("active-link").addClass("link");
        $("#tab4").removeClass("active-link").addClass("link");
        $("#tab5").removeClass("active-link").addClass("link");
        $("#tab6").removeClass("active-link").addClass("link");
        $("#tab7").removeClass("active-link").addClass("link");

        $("#tabContent2").hide();
        $("#tabContent3").hide();
        $("#tabContent4").hide();
        $("#tabContent5").hide();
        $("#tabContent6").hide();
        $("#tabContent7").hide();
        $("#MySetting").hide();
        $("#tabContent1").show();
    }
    function Tab2Click() {
        $("#tab2").addClass("active-link");
        $("#tab1").removeClass("active-link").addClass("link");
        $("#tab3").removeClass("active-link").addClass("link");
        $("#tab4").removeClass("active-link").addClass("link");
        $("#tab5").removeClass("active-link").addClass("link");
        $("#tab6").removeClass("active-link").addClass("link");
        $("#tab7").removeClass("active-link").addClass("link");

        $("#tabContent1").hide();
        $("#tabContent3").hide();
        $("#tabContent4").hide();
        $("#tabContent5").hide();
        $("#tabContent6").hide();
        $("#tabContent7").hide();
        $("#MySetting").hide();
        $("#tabContent2").show().load('@Url.Action("Tab2Content", "ServiceProvider")');
    }
    function Tab3Click() {
        $("#tab3").addClass("active-link");
        $("#tab1").removeClass("active-link").addClass("link");
        $("#tab2").removeClass("active-link").addClass("link");
        $("#tab4").removeClass("active-link").addClass("link");
        $("#tab5").removeClass("active-link").addClass("link");
        $("#tab6").removeClass("active-link").addClass("link");
        $("#tab7").removeClass("active-link").addClass("link");

        $("#tabContent1").hide();
        $("#tabContent2").hide();
        $("#tabContent4").hide();
        $("#tabContent5").hide();
        $("#tabContent6").hide();
        $("#tabContent7").hide();
        $("#MySetting").hide();
        $("#tabContent3").show().load('@Url.Action("Tab3Content", "ServiceProvider")');
    }
    function Tab4Click() {
        $("#tab4").addClass("active-link");
        $("#tab1").removeClass("active-link").addClass("link");
        $("#tab2").removeClass("active-link").addClass("link");
        $("#tab3").removeClass("active-link").addClass("link");
        $("#tab5").removeClass("active-link").addClass("link");
        $("#tab6").removeClass("active-link").addClass("link");
        $("#tab7").removeClass("active-link").addClass("link");

        $("#tabContent1").hide();
        $("#tabContent2").hide();
        $("#tabContent3").hide();
        $("#tabContent5").hide();
        $("#tabContent6").hide();
        $("#tabContent7").hide();
        $("#MySetting").hide();
        $("#tabContent4").show();
    }
    function Tab5Click() {
        $("#tab5").addClass("active-link");
        $("#tab1").removeClass("active-link").addClass("link");
        $("#tab2").removeClass("active-link").addClass("link");
        $("#tab3").removeClass("active-link").addClass("link");
        $("#tab4").removeClass("active-link").addClass("link");
        $("#tab6").removeClass("active-link").addClass("link");
        $("#tab7").removeClass("active-link").addClass("link");

        $("#tabContent1").hide();
        $("#tabContent2").hide();
        $("#tabContent3").hide();
        $("#tabContent4").hide();
        $("#tabContent6").hide();
        $("#tabContent7").hide();
        $("#MySetting").hide();
        $("#tabContent5").show().load('@Url.Action("Tab5Content", "ServiceProvider")');
    }
    function Tab6Click() {
        $("#tab6").addClass("active-link");
        $("#tab1").removeClass("active-link").addClass("link");
        $("#tab2").removeClass("active-link").addClass("link");
        $("#tab3").removeClass("active-link").addClass("link");
        $("#tab4").removeClass("active-link").addClass("link");
        $("#tab5").removeClass("active-link").addClass("link");
        $("#tab7").removeClass("active-link").addClass("link");

        $("#tabContent1").hide();
        $("#tabContent2").hide();
        $("#tabContent3").hide();
        $("#tabContent4").hide();
        $("#tabContent5").hide();
        $("#tabContent7").hide();
        $("#MySetting").hide();
        $("#tabContent6").show().load('@Url.Action("Tab6Content", "ServiceProvider")');
    }
    function Tab7Click() {
        $("#tab7").addClass("active-link");
        $("#tab1").removeClass("active-link").addClass("link");
        $("#tab2").removeClass("active-link").addClass("link");
        $("#tab3").removeClass("active-link").addClass("link");
        $("#tab4").removeClass("active-link").addClass("link");
        $("#tab5").removeClass("active-link").addClass("link");
        $("#tab6").removeClass("active-link").addClass("link");

        $("#tabContent1").hide();
        $("#tabContent2").hide();
        $("#tabContent3").hide();
        $("#tabContent4").hide();
        $("#tabContent5").hide();
        $("#tabContent6").hide();
        $("#MySetting").hide();
        $("#tabContent7").show().load('@Url.Action("Tab7Content", "ServiceProvider")');
    }
    function MySettingClick() {
        $("#tab1").removeClass("active-link").addClass("link");
        $("#tab2").removeClass("active-link").addClass("link");
        $("#tab3").removeClass("active-link").addClass("link");
        $("#tab4").removeClass("active-link").addClass("link");
        $("#tab5").removeClass("active-link").addClass("link");
        $("#tab6").removeClass("active-link").addClass("link");
        $("#tab7").removeClass("active-link").addClass("link");

        $("#tabContent1").hide();
        $("#tabContent2").hide();
        $("#tabContent3").hide();
        $("#tabContent4").hide();
        $("#tabContent5").hide();
        $("#tabContent6").hide();
        $("#tabContent7").hide();
        $("#MySetting").show().load('@Url.Action("MySetting", "ServiceProvider")');
        }

    function rowclicked(id) {
        $.post("/ServiceProvider/Service", { Id: parseInt(id) }, function (data) {
            $("#ServiceData").html(data.servicedate + "<br>Duration: " + parseFloat(data.duration) + " hrs.");
            $("#ServiceId").html(data.serviceid);
            $("#Extra").html(data.extra);
            $("#TotalCost").html(parseFloat(data.total) + "$");
            $("#CustomerName").html(data.cname);
            $("#ServiceAddress").html(data.addresses);
            $("#Distance").html(data.distance);
            $("#Comments").html(data.cmnt);
            $("#Accept_btn").prop('value', data.serviceid);
            $("#ServiceDetails").modal('show');
        });
    }
    function Urowclicked(id) {
        $.post("/ServiceProvider/Service", { Id: parseInt(id) }, function (data) {
            var d = new Date(data.servicedate);
            var d2 = new Date();
            var chours = d2.getTime();
            var addhours = (data.subtotal * 60) * 60 * 1000;
            var newd = new Date(chours + addhours);
            if (d <= newd) {
                $("#Complete_btn").removeClass("d-none").addClass("d-block");
            }
            else {
                $("#Complete_btn").removeClass("d-block").addClass("d-none");
            }
            $("#UServiceData").html(data.servicedate + "<br>Duration: " + parseFloat(data.duration) + " hrs.");
            $("#UServiceId").html(data.serviceid);
            $("#UExtra").html(data.extra);
            $("#UTotalCost").html(parseFloat(data.total) + "$");
            $("#UCustomerName").html(data.cname);
            $("#UServiceAddress").html(data.addresses);
            $("#UDistance").html(data.distance);
            $("#UComments").html(data.cmnt);
            $("#Cancel_btn").prop('value', data.serviceid);
            $("#Complete_btn").prop('value', data.serviceid);
            $("#UServiceDetails").modal('show');
        });
    }
    function Hrowclicked(id) {
        $.post("/ServiceProvider/Service", { Id: parseInt(id) }, function (data) {
            $("#HServiceData").html(data.servicedate + "<br>Duration: " + parseFloat(data.duration) + " hrs.");
            $("#HServiceId").html(data.serviceid);
            $("#HExtra").html(data.extra);
            $("#HTotalCost").html(parseFloat(data.total) + "$");
            $("#HCustomerName").html(data.cname);
            $("#HServiceAddress").html(data.addresses);
            $("#HDistance").html(data.distance);
            $("#HComments").html(data.cmnt);
            $("#HServiceDetails").modal('show');
        });
    }
    function Acccept_btnClicked(id) {
        $.post("/ServiceProvider/ServiceAccept", { Id: parseInt(id) }, function (data) {
            if (data == true) {
                alert("Service Acccepted successfully.");
                $("#ServiceDetails").modal('hide');
                Tab2Click();
            }
            else if (data == false) {
                alert("You already Accepted Service at same time.");
                Tab2Click();
            }
            else {
                alert(JSON.stringify(data));
                Tab7Click();
            }
        });
    }
    function Cancel_btnClicked(id) {
        $.post("/ServiceProvider/ServiceCancel", { Id: parseInt(id) }, function (data) {
            if (data == true) {
                alert("Service Cancelled successfully.");
                $("#UServiceDetails").modal('hide');
                Tab3Click();
            }
            Tab3Click();
        });
        Tab3Click();
    }
    function Complete_btnClicked(id) {
        $.post("/ServiceProvider/ServiceComplete", { Id: parseInt(id) }, function (data) {
            if (data == true) {
                alert("Service Completed successfully.");
                $("#UServiceDetails").modal('hide');
                Tab3Click();
            }

        });
        Tab3Click();
    }
    function BlockbtnClick(id) {
        $.post("/ServiceProvider/BlockCustomer", { Id: parseInt(id) }, function (data) {
            if (data == true) {
                alert("Customer Blocked successfully.");
                Tab7Click();
            }
            else if (data == false) {
                alert("Customer UnBlocked Successfully.");
                Tab7Click();
            }
            else {
                alert("error");
            }
        });
        Tab7Click();
    }
</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Helperland/Views/ServiceProvider/MyDetails.cshtml
@model Helperland.Models.SpProfileClass
@{
    Layout = null;
}
@using Microsoft.AspNetCore.Http;

<form id="DetailForm" method="post" asp-action="MyDetails" asp-controller="ServiceProvider">
    <ul id="ErrorFromDetails" class="pl-4 text-danger">
    </ul>
    <table width="100%" class="m-0 p-0">
        <tr>
            <td><h5>Basic Details</h5></td>
            <td align="right">
                <div class="avtar_image">
                    <img src="~/assets/img/@Model.UserProfilePicture" class="center_img">
                </div>
            </td>
        </tr>
    </table>
    <hr class="m-0 p-0"/>
    <div class="row m-0 p-0">
        <input class="form-control" asp-for="UserId" hidden />
        <div class="col-md-4 col-12">
            <label asp-for="FirstName">First Name</label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="col-md-4 col-12">
            <label asp-for="LastName">Last Name</label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="col-md-4 col-12">
            <label asp-for="Email">Email Address</label>
            <input asp-for="Email" class="form-control" readonly />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="row p-0 m-0 mt-1">
        <div class="col-md-4 col-12">
            <label asp-for="Mobile">Mobile Number</label>
            <div class="input-group">
                <span class="input-group-text">+49</span>
                <input asp-for="Mobile" type="number" class="form-control" name="mobile" />
                <span asp-validation-for="Mobile" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4 col-12">
            <label asp-for="DateOfBirth">Date of Birth</label>
            <input asp-for="DateOfBirth" type="date" class="form-control" />
            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
        </div>
        <div class="col-md-4 col-12">
            <label>Nationality</label>
            <select asp-for="NationalityId" class="form-control">
                <option value="1">Indian</option>
                <option value="2">Korean</option>
            </select>
        </div>
    </div>
    <hr />
    <label>Gender</label>
    <div class="row ml-2">
        <div class="form-check">
            <input asp-for="Gender" class="form-check-input" type="radio" value="1" />
            <label class="form-check-label mr-2">Male</label>
        </div>
        <div class="form-check">
            <input asp-for="Gender" class="form-check-input" type="radio" value="2" />
            <label class="form-check-label mr-2">Female</label>
        </div>
        <div class="form-check">
            <input asp-for="Gender" class="form-check-input" type="radio" value="3" />
            <label class="form-check-label mr-2">Rather Not to Say</label>
        </div>
    </div>
    <div class="form-group">
        <p>Select Avtar</p>
        <div class="avtar_selected">
            <div class="pl-2">
                <div class="avtar_image" id="Image1" onclick="AvtarClicked(this)">
                    <img src="~/assets/img/cap.png" class="center_img" id="AvtarImage1">
                </div>
            </div>
            <div class="pl-2">
                <div class="avtar_image" id="Image2" onclick="AvtarClicked(this)">
                    <img src="~/assets/img/separator.png" class="center_img" id="AvtarImage2">
                </div>
            </div>
            <div class="pl-2">
                <div class="avtar_image" id="Image3" onclick="AvtarClicked(this)">
                    <img src="~/assets/img/calendar-book-service.png" class="center_img" id="AvtarImage3">
                </div>
            </div>
            <div class="pl-2">
                <div class="avtar_image" id="Image4" onclick="AvtarClicked(this)">
                    <img src="~/assets/img/smiley.png" class="center_img" id="AvtarImage4">
                </div>
            </div>
            <div class="pl-2">
                <div class="avtar_image" id="Image5" onclick="AvtarClicked(this)">
                    <img src="~/assets/img/down-arrow.png" class="center_img" id="AvtarImage5">
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        My Addresses
        <hr class="m-0 p-0" />
        <div class="m-0 p-0">

            <div class="row mt-0">
                <div class="col-md-4 col-12">
                    <label>Street name*</label>
                    <input asp-for="AddressLine1" class="form-control" id="FAddressLine1" placeholder="Street name" />

                </div>
                <div class="col-md-4 col-12">
                    <label>House number*</label>
                    <input asp-for="AddressLine2" class="form-control" id="FAddressLine2" placeholder="House number" />
                </div>
                <div class="col-md-4 col-12">
                    <label>Postal Code*</label>
                    <input asp-for="PostalCode" name="PostalCode" class="form-control" id="FZip" placeholder="Postal Code" />
                </div>
            </div>
            <div class="row  mt-1">
                <div class="col-md-4 col-12">
                    <label>City*</label>
                    <input asp-for="City" class="form-control" id="FCity" placeholder="Surat">
                </div>

            </div>
        </div>
    </div>
    <hr class="m-0 p-0" />
    <div class="form-group">
        <button onclick="SubmitDetailForm()" value="Save" class="rounded_btn px-3">Save</button>
    </div>

</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}